### ISSUE TITLE
SDL_image port

### ISSUE THREAD

**Issue by JayFoxRox** [XboxDev/nxdk#167]
@SoundAxis has prototyped a SDL_image port in https://github.com/SoundAxis/nxdk/tree/master/lib/sdl/SDL2_image

This would possibly benefit from #163 and #164 by using those existing ports of the latest versions. Someone should check wether this is possible, so we can use an existing SDL_image repository without changes.

If not possible to use existing libjpeg and libpng ports, someone should reconstruct the history of SDL_image to extract nxdk specific patches.

**Comment by SoundAxis** [comment]
SDL_Image:
The version in my repo works, however, there is a bug in the SDL_Image auto-detection of the image type. I was just bypassing it for the original tests, but I suspect it might be an endian problem or similar due to me just hacking around their build scripts.

Jpg & png:
The work for libjpeg and libpng should both be in my repo already. The work (for both really) was replacing POSIX file calls with ANSI file calls, and needing to define float functions. "LIBPNG_HACKS_SRCS"

**Comment by JayFoxRox** [comment]
> The work for libjpeg and libpng should both be in my repo already

I'm aware there's port of those in your code. However, the versions used in SDL_image are older and they are not exposed outside of SDL_image, reaching them would be hacky (so people could easily use SDL_image, but using zlib, libpng or libjpeg alone). Maintaining 2 ports of each library in slightly different versions (for stand-alone use and SDL_image) is hacky, too.

The ports in #162 [zlib] #163 [libpng] and #164 [libjpeg-turbo] are of the latest versions and can be used standalone. It will be easier to upgrade them individually, too.

I'd imagine that SDL_image can be configured to use libraries out-of-tree (as would be the case for dynamic-linking). If that can be done, SDL_image doesn't have to be modified at all (avoiding your changes in those libraries) and we'd only require a makefile (so we could use an official SDL_image repository / submodule).

**Comment by JayFoxRox** [comment]
@thrimbor has a variant here: https://github.com/thrimbor/nxdk/commit/e5db4b9626b0b5a052b3cd0ac3a825bcebd44b25

I assume that it will be upstreamed in the future.
