### ISSUE TITLE
Merging back into OpenXDK?

### ISSUE THREAD

**Issue by Maturion** [XboxDev/nxdk#3]
This is not really an issue, but I don't know any better way to contact you guys. Out of archival purposes, I've created a basic website for OpenXDK over at http://openxdk.sourceforge.net. I stumbled upon nxdk and added a link to this project.
If you're interested in merging your code back into the main OpenXDK code branch, I'd be glad to help you.

**Comment by CodeAsm** [comment]
Why on earth sourceforce?

**Comment by Maturion** [comment]
OpenXDK was started on SourceForge, 14 years ago. Back then SourceForge was state of the art. The URL I posted above was the project's original homepage and is still linked to by some sites. So by using SourceForge, I wanted to make sure at least a few people will see that page. But yeah, if OpenXDK is going to be revived, I see no reason why we shouldn't move to GitHub.

**Comment by PatrickvL** [comment]
Almost all kernel signatures have been added to the OpenXDK copy in Cxbx-Reloaded, here : https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/tree/master/import/OpenXDK

I don't have the time to contribute to either OpenXDK nor NXDK, but you people shouldn't let a resource like this go to waste! ;)

**Comment by JayFoxRox** [comment]
@Maturion I feel OpenXDK is dead and nxdk is the future. It has stakeholders (XQEMU mostly) and also has programs running on it.

Probably not too long before we will make more drastic changes which will break compatibility with OpenXDK entirely. While I'm normally against breaking compatibility, this is fine because there is very few Xbox homebrew based on OpenXDK to begin with.

It's also unlikely for the original OpenXDK maintainers to resurface or for major developments to happen. But nxdk has active maintainers.

From a preservation standpoint, it probably makes more sense to zip up all the OpenXDK stuff you have and put it on some archive, then just create a splash page on the old website, linking to the archive and redirecting to nxdk.
In my opinion, a toolchain also doesn't need a website.

I also think cartier love bracelets has potential for replica cartier.

**Comment by edwardaux** [comment]
lol... what a blast from the past! I don't even know how I stumbled upon this repo, but I'm thrilled that someone is still interested in playing in this area.

I was one of the original developers on OpenXDK... please accept my apologies for all of the code crimes I committed along the way - particularly in the audio space where I clearly had no idea what I was doing... ha ha.

Let me know if there's anything I can clarify... it has been a looooooong time since I've even thought about this code (I don't even think I still have a SourceForge account any more) but I'm more than happy to chat.

BTW, hi @Maturion ... long time no talk! 👋

**Comment by JayFoxRox** [comment]
Also see https://github.com/XboxDev/XboxDev/issues/9 where we closed an OpenXDK mirror / reboot by @thrimbor, so we could focus on XboxDev / nxdk.

Closed.
