### ISSUE TITLE
Stack-overflow does not halt execution

### ISSUE THREAD

**Issue by JayFoxRox** [XboxDev/nxdk#359]
When the stack overflows, we only print a message (potentially causing more stack overflows?), but we never halt execution:

https://github.com/XboxDev/nxdk/blob/0e279cc5cfc398f9c9bcd7e2f8c390f4e9e59df6/lib/xboxrt/c_runtime/check_stack.c#L14-L22

I assume this is a critical issue, because it can corrupt the system state (accidentally accessing hardware in the overflown region). Feel free to remove the "critical" label if this can not happen.

This is an issue in the application that can be worked around by better algorithms or increasing the stack size (if necessary). However, a stack overflow should safely halt the system, rather than continuing with a broken state.

**Comment by thrimbor** [comment]
> (potentially causing more stack overflows?)

The message printing occurs before an actual overflow happens. It's also important to note that this can only catch "fast" overflows, e.g. when trying to reserve a buffer on the stack that's larger than a page, because only then will the compiler insert calls to `__chkstk`.
Other problems, like slowly overflowing the stack by doing infinite recursion, can't be catched by this. Unless the kernel uses guard pages (which is something I believe I never checked), there's nothing protecting against this.

> I assume this is a critical issue, because it can corrupt the system state (accidentally accessing hardware in the overflown region). Feel free to remove the "critical" label if this can not happen.
> 
> This is an issue in the application that can be worked around by better algorithms or increasing the stack size (if necessary). However, a stack overflow should safely halt the system, rather than continuing with a broken state.

It's definitely a problem, though I wonder whether we should really just halt the system, or maybe even check for debugger presence and give that the opportunity to debug the issue. On a retail system halting is probably the only option (or maybe rebooting is better then?), but when developing / debugging an issue it could get quite annoying.
