### ISSUE TITLE
Improve `XBE_TITLE` of nxdk samples

### ISSUE THREAD

**Issue by JayFoxRox** [XboxDev/nxdk#372]
I think we should consider doing `XBE_TITLE = "nxdk sample: gamma-fade"` instead of `XBE_TITLE = gamma-fade`.
If this doesn't work (spaces in title), then we should fix it so that it does work.

Adding quotes should help to clarify that leading whitespaces are not part of the name (are they?). It also shows how to include whitespaces in the XBE title.

**Comment by kosmas12** [comment]
Using quotes along with an escape sequence for spaces inside the quotes ("nxdk\ gamma-fade\ sample") works for me. Using quotes without any escape sequence for spaces ("nxdk gamma-fade sample") says that there is an unterminated quote string, I suspect it might be because it stops when it sees a space in nxdk and sees there is no quote to terminate the string, though I might be wrong.
