### ISSUE TITLE
Is it possible to port this SDK over to Rust using something like Bindgen?

### ISSUE THREAD

**Issue by c9d5e1** [XboxDev/nxdk#415]
Is it possible to port this SDK over to Rust using something like Bindgen?

**Comment by dracc** [comment]
I don't know, why don't you give it a try? Most of the projects' current devs probably find this a non-goal.

**Comment by thrimbor** [comment]
This is more of a question rather than an actual issue, and as such is better suited for discussing in e.g. our Discord.

> Is it possible to port this SDK over to Rust using something like Bindgen?

Bindgen isn't for porting stuff to Rust, it's for automatically creating Rust bindings for libraries. If that is what you actually meant, I don't see anything standing in the way of trying that, but be aware that Rust might depend on additional runtime features we don't provide yet.
