### ISSUE TITLE
don't enable limit 64m by default in cxbe

### ISSUE THREAD

**Issue by GXTX** [XboxDev/nxdk#484]
And allow configurable. A project I have requires this and the kernel seems to actually check this flag and does very odd things when trying to malloc large blocks (~63MB) with it enabled.

**Comment by JayFoxRox** [comment]
Please *always* explain why an issue was closed.

> A project I have requires this and the kernel seems to actually check this flag

To me, this doesn't sound like the default should be changed, but just that the configuration option should be exposed in a way that makes it easier to toggle it (at least if it's a common request).

> does very odd things when trying to malloc [...]

This could be an independent problem.
However, you are probably running out of memory; so some unexpected behavior should be expected.
I'm not sure if nxdk handles this condition correctly (yet).

Even with the XBE flag, a couple of kernels won't give you more than 64MiB, because the kernel usually reserves the second region of 64MiB for a different allocator (I think). So the nxdk implementation of `malloc` might not work for your use-case.

> [...] large blocks (~63MB) with it enabled.

You shouldn't have to allocate such large memory blocks anyway. There's probably no need for it either.
Your memory region will be fragmented / paged, so it's probably "slow" memory and you couldn't use it from the GPU either (which is where you'd typically require this much memory).

The only possible use-case I can think of are niche-cases for emulation (but even there I'd consider going with smaller memory and compressed chunks/compression) or large banks of audio effects (because the APU *can* do paging) or disc images.

You'll probably want some form of streaming or more sophisticated memory-management instead (compared to what `malloc` offers).

**Comment by GXTX** [comment]
Yes should probably say why, iirc there's another post about having such things configurable (or it's noted in source). I should rewrite to not use such a large block but it's simple for me to understand and get working. I also found that I don't actually need the flag hence me closing. My application runs and allocs as needed on a 64m machine. See: https://github.com/GXTX/BadApple_SDL/tree/use_mem I'm probably super close to using more than I should but it runs fine with audio on the correct NXDK fork and works as expected.
