### ISSUE TITLE
XBE crashes on start, when declaration added in class.

### ISSUE THREAD

**Issue by hcfcoder** [XboxDev/nxdk#496]
This issue was discussed in the discord channel, and in fact there is a workaround adding "-fno-threadsafe-statics" to the compiler flags (thanks to Thrimbor for that hint!!): it seems that adding certain declarations in a class, makes the program crash on start (even if that code is not executed). I built a minimal sample that has this behaviour and uploaded it here:

https://gist.github.com/hcfcoder/7d7cde1f55000d160084869f1c2fd141

In that sample, this declaration in the "Logger" class makes the program crash on boot:

std::stringstream m_str;

It crashes if we put it in the public part of the class, and also if we put it in the private part of the class too. On the other hand, putting that same declaration in the main function of the program, does not crash.

**Comment by thrimbor** [comment]
I've identified the root cause, but it's a tricky thing to solve.

My initial suspicion was correct that this is caused by the thread-safe statics initialization. Nested inside the constructor of `std::stringstream` is a call to `locale& locale::__global()`, which contains a static variable called `g`. When enabling thread-safe statics initialization, the code to initialize `g` is never run, making it a null pointer, which is returned and subsequently dereferenced, making the code crash.

The code that decides to skip the initialization of `g` is generated by LLVM, and depends on `_Init_thread_epoch`. This is a thread-local variable however, which is problematic, since global constructors are called from the initial thread created by the kernel, which is not able to use thread-local storage.

Now, this is bad, obviously. We shouldn't run constructors from a thread that crashes when they're doing perfectly legal things. The solution would be to move constructor calls from the initial thread to the main-thread, which has working TLS. Which unfortunately brings new problems, as we currently have constructors that have to run *before* creating any threads.

So we need to do two things:
1. Move the normal constructor calls from the initial thread to the main-thread
2. Figure out a way to run some constructors (such as `fls_init()`) in the initial thread instead

We can probably solve the latter by duplicating the mechanisms we use to register and call normal constructors, but that's more work than I have time for today.

**Comment by hcfcoder** [comment]
Thank you very much! Great work!!
