### ISSUE TITLE
Optimization flags not set on compiler even if `DEBUG != y`

### ISSUE THREAD

**Issue by abaire** [XboxDev/nxdk#510]
Not sure if it's intentional or not; I naively assumed that failing to set `DEBUG=y` would imply full optimization. Would it make sense to set them as `NXDK` flags?

E.g.,
```
ifeq ($(DEBUG),y)
NXDK_ASFLAGS += -g -gdwarf-4
NXDK_CFLAGS += -g -gdwarf-4
NXDK_CXXFLAGS += -g -gdwarf-4
NXDK_LDFLAGS += -debug
else
NXDK_ASFLAGS += -O3
NXDK_CFLAGS += -O3
NXDK_CXXFLAGS += -O3
endif
```

If not, should the `README.md` or some other spot be updated to notify app writers that they might want to consider opting in to higher levels of optimization in their `Makefile`?

**Comment by thrimbor** [comment]
That's on purpose. Just like other toolchains/compilers, you don't get any optimization flags by default - nxdk is trying to wrap clang as thinly as possible here. The special treatment of `DEBUG` is because the normal debug flag (`-g`) is not enough to generate debug info readable by gdb, while `LTO` gets special treatment due to whitespace issues in Docker (see #488).

For what would be considered a release build, `make LTO=y CFLAGS=-O2 CXXFLAGS=-O2` is what I would use. This is also what the `nxdk-lto` docker image is built with (you still have to set these flags for your own code that you build with it).

The plan for the future is to restructure how nxdk is built, and to provide compiler wrappers that can either be used directly, bypassing our Makefile issues and magic flag handling, or can get used from something like CMake, which would then handle that for you (this is something both I and jfr worked on in the past, but I don't consider my changes to be upstreamable yet).

**Comment by abaire** [comment]
Got it, thanks!

**Comment by thrimbor** [comment]
Ok, looks like this can be closed then. In case you weren't aware already, we have a [Discord](https://discord.gg/XUDsBYD) - it's a little more interactive than GH issues.
