### ISSUE TITLE
winapi: missing `<shlwapi.h>`

### ISSUE THREAD

**Issue by glebm** [XboxDev/nxdk#593]

**Comment by LukeUsher** [comment]
This makes perfect sense; the Xbox is *not* a windows platform.

nxdk uses a WinAPI subset purely because the Xbox Kernel is designed to work with a WinAPI-style environment, but it is not win32.

The xbox (even with official Microsoft tools) does not have any of the major windows components like shell, locale, etc.

**Comment by glebm** [comment]
Looks like we just have to sprinkle `&& !defined(NXDK)` throughout, including dependent libraries.
