### ISSUE TITLE
SDL_Cond linker errors

### ISSUE THREAD

**Issue by glebm** [XboxDev/nxdk#600]
Looks like there are some linking issues with `SDL_Cond` stuff:

```
lld: error: undefined symbol: _SDL_CondSignal
>>> referenced by Source/CMakeFiles/libdevilutionx.dir/dthread.cpp.obj:(public: void __thiscall devilution::SdlCond::signal(void))

lld: error: undefined symbol: _SDL_DestroyCond
>>> referenced by Source/CMakeFiles/libdevilutionx.dir/dthread.cpp.obj:(public: __thiscall devilution::SdlCond::~SdlCond(void))

lld: error: undefined symbol: _SDL_CondWait
>>> referenced by Source/CMakeFiles/libdevilutionx.dir/dthread.cpp.obj:(public: void __thiscall devilution::SdlCond::wait(class devilution::SdlMutex &))

lld: error: undefined symbol: _SDL_CreateCond
```

**Comment by kosmas12** [comment]
Good day!

I took a look at the source (and the error), and it seems that `SdlCond` is part of the source code of the project, and it also seems that it's got some SDL2->SDL1.2 backports, which I'm not sure how well they would work/if they are necessary here since we got SDL2 in nxdk. I recommend disabling USE_SDL1 if you haven't already. (NOTE: I don't know how/if that project supports native SDL2 either). Also, for faster help, I recommend joining the XboxDev Discord server, where we can help in a more direct way than we can from over here.

**Comment by glebm** [comment]
> SdlCond is part of the source code of the project,

That just wraps the SDL code.

>  SDL2->SDL1.2 backports

There aren't any, the backports are the other way around and only when SDL1 is used. For NXDK we use SDL2.

The linker errors are for symbols declared in SDL itself!

**Comment by kosmas12** [comment]
Ah, I see. I am sorry, I'm not too familiar with the code for that project or the inner workings of SDL.

**Comment by glebm** [comment]
No worries! The fix linked above by @thrimbor fixes the issue :tada:
